module.exports = {
  blog: {
    id: 'id',
    title: 'title',
    slug: 'slug',
    description: 'description',
    image: 'image',
    category_id: 'category_id',
    category_name: 'category_name',
    updated_at: 'updated_at',
  },
  blogDetail: {
    id: 'id',
    slug: 'slug',
    image: 'image',
    title: 'title',
    description: 'description',
    created_at: 'createdAt',
    time: 'time',
    views: 'views',
    category_id: 'category_id',
    category_name: 'category_name',
    updated_at: 'updated_at',
  },
  blogWithOutId: {
    slug: 'slug',
    image: 'image',
    title: 'title',
    description: 'description',
    created_at: 'createdAt',
    time: 'time',
    views: 'views',
    category_id: 'category_id',
    category_name: 'category_name',
    updated_at: 'updated_at',
  },
}
