module.exports = {
  cart: {
    name: 'name',
    slug: 'slug',
    image: 'image',
    banner_image: 'banner_image',
  },
  cart_product: {
    id: 'id',
    quantity: 'quantity',
    product_id: 'product_id',
    flavor_name: 'flavor_name',
    flavor_id: 'flavor_id',
    mrp_price: 'mrp_price',
    customer_price: 'customer_price',
    size: 'size',
    display_image: 'display_image',
    name: 'name',
    product_stock_detail_id: 'product_stock_detail_id',
    product_stock_id: 'product_stock_id',
    slug: 'slug',
    best_before: 'best_before',
    is_sold: 'is_sold',
    freebie: 'freebie',
    bulk_quantity_offer: 'bulk_quantity_offer',
    bulk_quantity_offer_value: 'bulk_quantity_offer_value',
    ProductStocks: 'ProductStocks',
  },
}
