module.exports = {
  product: {
    id: 'id',
    name: 'name',
    size: 'size',
    slug: 'slug',
    rating: 'rating',
    is_sold: 'is_sold',
    is_favorite: 'is_favorite',
    mrp_price: 'mrp_price',
    customer_price: 'customer_price',
    ProductViewCounts: 'ProductViewCounts',
    display_image: 'display_image',
  },
  product_cart: {
    id: 'id',
    name: 'name',
    size: 'size',
    slug: 'slug',
    rating: 'rating',
    is_sold: 'is_sold',
    is_favorite: 'is_favorite',
    product_stock_detail_id: 'product_stock_detail_id',
    bulk_quantity_offer_value: 'bulk_quantity_offer_value',
    product_stock_id: 'product_stock_id',
    mrp_price: 'mrp_price',
    customer_price: 'customer_price',
    ProductViewCounts: 'ProductViewCounts',
    quantity: 'quantity',
    display_image: 'display_image',
    flavor: 'flavor',
    bulk_quantity_offer: 'bulk_quantity_offer',
    freebie: 'freebie',
  },
  product_detail: {
    id: 'id',
    name: 'name',
    slug: 'slug',
    description: 'description',
    authenticity: 'authenticity',
    best_before: 'best_before',
    country_of_origin: 'country_of_origin',
    delivery_charge: 'delivery_charge',
    how_to_use: 'how_to_use',
    ingredients: 'ingredients',
    is_sold: 'is_sold',
    return_policy: 'return_policy',
    ProductStocks: 'ProductStocks',
    rating_and_reviews: 'rating_and_reviews',
    in_cart: 'in_cart',
    discount_type: 'discount_type',
    rating: 'rating',
    is_favorite: 'is_favorite',
    discount_value: 'discount_value',
    freebie: 'freebie',
  },
}
