module.exports = {
  category: {
    id: 'id',
    name: 'name',
    description: 'description',
    image: 'image',
    app_image: 'app_image',
    web_image: 'web_image',
    status: 'status',
    sub_category: 'sub_category',
    sub_category_count: 'sub_category_count',
    sub_category_ids: 'sub_category_ids',
    products_count: 'products_count',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
  },
  subcategory: {
    id: 'id',
    name: 'name',
    description: 'description',
    icon_image: 'icon_image',
    app_image: 'app_image',
    web_image: 'web_image',
    status: 'status',
    sub_category: 'sub_category',
    sub_category_count: 'sub_category_count',
    products_count: 'products_count',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
  },
  categoryDetails: {
    id: 'id',
    name: 'name',
    description: 'description',
    sub_category: 'sub_category',
    sub_category_count: 'sub_category_count',
    image: 'image',
    app_image: 'app_image',
    web_image: 'web_image',
    icon_image: 'icon_image',
    status: 'status',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
  },
  activeCategoryList: {
    id: 'id',
    name: 'name',
    sub_category: 'sub_category',
  },
  activeSubCategoryList: {
    id: 'id',
    name: 'name',
  },
}
