module.exports = {
  customer: {
    id: 'id',
    name: 'name',
    email: 'email',
    mobile: 'mobile',
    image: 'image',
    gender: 'gender',
    dob: 'dob',
    status: 'status',
    is_cod_active: 'is_cod_active',
    otp: 'otp',
    user_type: 'user_type',
    is_use_app: 'is_use_app',
    referrer_code: 'referrer_code',
    state: 'state',
    pincode: 'pincode',
    orders_count: 'orders_count',
    referral_count: 'referral_count',
    nutricash: 'nutricash',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
  },
  customerDetail: {
    id: 'id',
    name: 'name',
    email: 'email',
    mobile: 'mobile',
    image: 'image',
    gender: 'gender',
    dob: 'dob',
    is_cod_active: 'is_cod_active',
    referrer_code: 'referrer_code',
    pincode: 'pincode',
    nutricash: 'nutricash',
    status: 'status',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
  },
  customerAddressList: {
    id: 'id',
    customer_id: 'customer_id',
    receiver_name: 'receiver_name',
    address_1: 'address_1',
    address_2: 'address_2',
    city: 'city',
    pincode: 'pincode',
    state: 'state',
    mobile_no: 'mobile_no',
    status: 'status',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
  },
  customerAddressDetails: {
    id: 'id',
    customer_id: 'customer_id',
    receiver_name: 'receiver_name',
    address_1: 'address_1',
    address_2: 'address_2',
    city: 'city',
    pincode: 'pincode',
    state: 'state',
    status: 'status',
    mobile_no: 'mobile_no',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
  },
}
