module.exports = {
  featureProduct: {
    id: 'id',
    product_id: 'product_id',
    product_name: 'product_name',
    product_image: 'product_image',
    sort_order: 'sort_order',
    start_date: 'start_date',
    name: 'name',
    end_date: 'end_date',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
  },
  featuredCategoryList: {
    id: 'id',
    name: 'name',
    slug: 'slug',
    start_date: 'start_date',
    end_date: 'end_date',
    type: 'type',
    status: 'status',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
  },
  featuredCategoryDetail: {
    id: 'id',
    name: 'name',
    start_date: 'start_date',
    end_date: 'end_date',
    image: 'image',
    type: 'type',
    slug: 'slug',
    featured_products: 'featured_products',
    status: 'status',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
  },
}
