module.exports = {
  product: {
    id: 'id',
    name: 'name',
    slug: 'slug',
    category: 'category',
    display_image: 'display_image',
    brand: 'brand',
    flavors_count: 'flavors_count',
    status: 'status',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
  },
  viewProductDetail: {
    id: 'id',
    name: 'name',
    slug: 'slug',
    category_id: 'category_id',
    sub_category_id: 'sub_category_id',
    brand_id: 'brand_id',
    how_to_use: 'how_to_use',
    description: 'description',
    is_cod: 'is_cod',
    delivery_charge: 'delivery_charge',
    discount_type: 'discount_type',
    country_of_origin: 'country_of_origin',
    authenticity: 'authenticity',
    ingredients: 'ingredients',
    return_policy: 'return_policy',
    display_image: 'display_image',
    tax: 'tax',
    hsn: 'hsn',
    discount_value: 'discount_value',
    freebie: 'freebie',
    specification: 'specification',
    product_flavours: 'productFlavours',
    product_stocks: 'productStocks',
    product_images: 'productImages',
    status: 'status',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
  },
  activeProducts: {
    id: 'id',
    name: 'name',
  },
  productDetails: {
    id: 'id',
    name: 'name',
    description: 'description',
    delivery_charge: 'delivery_charge',
    country_of_origin: 'country_of_origin',
    how_to_use: 'how_to_use',
    display_image: 'display_image',
    product_reviews: 'productReview',
    product_detail: 'productDetail',
    authenticity: 'authenticity',
    return_policy: 'return_policy',
    ingredients: 'ingredients',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
  },
  sortedProductList: {
    id: 'id',
    name: 'name',
    display_image: 'display_image',
    created_at: 'createdAt',
    updated_at: 'updatedAt',
  },
  flavourLists: {
    id: 'id',
    name: 'flavor_name',
  },
}
